### PR TITLE
setup.py for wifijammer

### PR DESCRIPTION
**Pull request by 0x90**
setup.py added for installation process
wifijammer.py renamed to wifijammer

Now it can be easily installable by running:
pip install "git+https://github.com/0x90/wifijammer#egg=wifijammer"

### CODE REVIEW

**Comment by ih8ppl** [comment]
Man, you are awesome! Script runs flawless! when the little punk next door cranks up pandora and starts shaking the walls this shuts him up without me having to deauth him through aireplay every 2 or 3 minutes! My ears, kids and sanity owe you a debt of gratitute.

**Comment by captainven** [comment]
How to install this when i go tu putty and type pip install git+https://github.com/0x90/wifijammer#egg=wifijammer...it not worked

**Comment by captainven** [comment]
Can you make this script support for openwrt,thanks!<3

**Comment by DanMcInerney** [comment]
Thanks! Merged.

**Pull request merged**
