### PR TITLE
allow to specify multiple target accesspoints (by bssid or essid)

### PR DESCRIPTION
**Pull request by tintinweb**
* added handling for multiple --accesspoint filters `--accesspoint` now takes essid or bssid
      tracks bssid's for essid's
      essid is case sensitive
      bssid is not case sensitive
* added utf8 coding hint
* fixed wrong indentation (sniff())

Allows to specify multiple targets by either bssid or essid. Selection by essid is way more handy than bssid. Here's an example to jam `FreeWifi`, `UnitedCoffee` and others:

```tin@debian8:~/wifijammer$ sudo python wifijammer.py --accesspoint "FreeWifi" ff:53:cc:f2:8A:E3 ba:df:00:00:00:0d "UnitedCoffee" Starbucks```

### CODE REVIEW

**Comment by DanMcInerney** [comment]
merged the other one.

**Comment by tintinweb** [comment]
@DanMcInerney this one is actually different from #61 as it allows to specify multiple target bssids or essids whereas #61 allows to specify bssids to skip.

**Comment by DanMcInerney** [comment]
Can you fix the minor conflicts and I'll merge?

**Comment by tintinweb** [comment]
done 👍

**Pull request merged**
