### PR TITLE
Fix: Cause a reboot the network manager

### PR DESCRIPTION
**Pull request by tailot**
It prevents restarting the network manager.

### CODE REVIEW

**Comment by phr34k0** [comment]
Reboot is because of line 399

>         os.system('service network-manager restart')

Personally i do

>         except Exception as msg:
>         remove_mon_iface(mon_iface)
>         os.system('ifconfig %s down')

and dont forget the interface = args.interface on line 55

> def get_mon_iface(args):
>     global monitor_on
>     monitors, interfaces = iwconfig()
>     if args.interface:
> 	interface = args.interface
>         monmode = start_mon_mode(interface)
>         return monmode

as -i argument don't really work as it suppose to

with those changes the script works flawlessly on any nix even nethunter on mobile. Author didn't respond to the issue so...

**Comment by DanMcInerney** [comment]
I'll check this out in a while, I just got kali rolling so I'll check for compat here soon.

**Comment by DanMcInerney** [comment]
So I'm terrible with git and there was a merge conflict. I ended up just wgetting your version and uploading it. A poor man's merge.

**Comment by phr34k0** [comment]
Uh.. git clone https://github.blablabla? xD

**Comment by DanMcInerney** [comment]
Hah, to be fair I can clone it, but the whole command line merge when there's conflicts between master and the pull branch eludes me still. So I just d/l'd it and pushed it to overwrite any merge conflicts.

**Comment by phr34k0** [comment]
Lel

**Pull request closed without merging**
