### PR TITLE
wifijammer as a python package

### PR DESCRIPTION
**Pull request by llazzaro**
this will allow to install the project via pip

```
pip install git+https://github.com/llazzaro/wifijammer.git
```

after installation the command "wifijammer.py" will be available to be execute like any other command.

### CODE REVIEW

**Comment by llazzaro** [comment]
for the record I just moved the wifijammer.py to other path, no code was changed

**Comment by raspbianpi3** [comment]
Hi llazzaro..I couldn't install the project link..have any idea or solutions for this?

**Comment by llazzaro** [comment]
please explain more why you couldn't install the project.

**Comment by Pakket** [comment]
Make sure you have the dependency packages installed first.

**Comment by llazzaro** [comment]
@Pakket  my branch should install all required python packages

**Comment by raspbianpi3** [comment]
@llazzaro this link should be typed in the terminal right ?

**Comment by raspbianpi3** [comment]
I typed this in terminal and it showed compile failed
Error:command 'arm-Linux-gnueabinhf-gcc' failed with exit status 1.

**Comment by raspbianpi3** [comment]
Pls help me step by step Coz I'm still new to this

**Comment by llazzaro** [comment]
Sorry I can't help you. Github issue tracker is for reporting bugs.

**Comment by vxbinaca** [comment]
Shouldn't this be in pip instead?

**Comment by llazzaro** [comment]
@vxbinaca in order to be in pip you need to make a package first.
I published a similar project on github recently https://github.com/llazzaro/wifi_tools. 
Some code was based on wifijammer (or ideas).

**Pull request closed without merging**
