### PR TITLE
multiple skip addresses

### PR DESCRIPTION
**Pull request by ContextSwitchWang**
Why don't we allow multiple skip mac addresses?

### CODE REVIEW

**Comment by tintinweb** [comment]
Hi,

You'll have to init `skip` otherwise this will result in a `TypeError` while trying to iterate `None`. Here's a patch:

```diff --git a/wifijammer.py b/wifijammer.py
index 23da44e..4943ae8 100755
--- a/wifijammer.py
+++ b/wifijammer.py
@@ -33,6 +33,7 @@ def parse_args():
     parser.add_argument("-s",
                         "--skip",
                         nargs='*',
+                        default=[],
                         help="Skip deauthing this MAC address. \
                                 Example: -s 00:11:BB:33:44:AA")
     parser.add_argument("-i",
@@ -427,7 +428,7 @@ if __name__ == "__main__":
     DN = open(os.devnull, 'w')
     lock = Lock()
     args = parse_args()
-    args.skip = [addr.lower() for addr in args.skip]
+    args.skip = map(str.lower, args.skip)
     monitor_on = None
     mon_iface = get_mon_iface(args)
     conf.iface = mon_iface
```

**Comment by ContextSwitchWang** [comment]
I think you are right.

**Comment by ContextSwitchWang** [comment]
But using map will yield a map object on python3, that may cause problems. I think it is better to save args.skip just as a list.

**Comment by ContextSwitchWang** [comment]
And every time we use args skip it has to be recalculated from a map object.

**Comment by tintinweb** [comment]
python3 will panic anyway because of print not being a function :) But thanks for the py3 hint, didn't know that

**Comment by ContextSwitchWang** [comment]
You are right. Python 3 won't work anyway...

**Pull request closed without merging**
